version: '3'

services:

    app:
        container_name: app_node
        build: 
            context: ./node
        networks: 
            - node-network
        volumes: 
            - ./node:/usr/src/app
        tty: true
        ports: 
            - "3000:3000"
        depends_on: 
            - db
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=102030
        networks: 
            - node-network
        ports: 
            - 3306:3306

networks: 
    node-network:
        driver: bridge
